Support library (#93)
* System library to query memory, exe name, source location of addresses
* Table.h is now an install target

diff --git a/scripts/typeart-tmpl.sh.in b/scripts/typeart-tmpl.sh.in
--- a/scripts/typeart-tmpl.sh.in
+++ b/scripts/typeart-tmpl.sh.in
@@ -20,6 +20,7 @@ function parse_cmd_line() {
   with_intercept=0
   with_thread=0
   skip_typeart=0
+  compile_flags=""
 
   shift # skip over $1
   while (("$#")); do
@@ -67,6 +68,15 @@ function parse_cmd_line() {
         shift
       fi
       ;;
+      --compile_flags)
+        if [ -n "$2" ]; then
+          compile_flags="$2"
+          shift 2
+        else
+          echo "Error: argument for $1 is missing." >&2
+          shift
+        fi
+        ;;
     *) # preserve other arguments
       ta_more_args="$ta_more_args $1"
       shift
@@ -82,6 +92,10 @@ function parse_cmd_line() {
   if [ -z "${exe_file}" ]; then
     # use filename(source_file).o
     exe_file="${source_file%.*}".exe
+  fi
+
+  if [ -z "${compile_flags}" ]; then
+    compile_flags=""
   fi
 }
 
@@ -157,17 +171,17 @@ function make_no_optim() {
   # Order: heap and stack/global together, no optimization pass
   if [ $skip_typeart == 0 ]; then
     $compiler ${omp_flags} ${typeart_includes} ${typeart_san_flags} \
-      -O1 -Xclang -disable-llvm-passes -S -emit-llvm "${source_file}" -o - |
+      -O1 ${compile_flags} -Xclang -disable-llvm-passes -S -emit-llvm "${source_file}" -o - |
       $opt_tool ${typeart_plugin} ${typeart_combined_mode_args} ${ta_more_args} |
       $llc_tool -x=ir ${llc_flags} -o "${object_file}"
   else
     # First create types.yaml:
     $compiler ${omp_flags} ${typeart_includes} ${typeart_san_flags} \
-      -O1 -Xclang -disable-llvm-passes -S -emit-llvm "${source_file}" -o - |
+      -O1 ${compile_flags} -Xclang -disable-llvm-passes -S -emit-llvm "${source_file}" -o - |
       $opt_tool ${typeart_plugin} ${typeart_combined_mode_args} ${ta_more_args} >/dev/null
 
     $compiler ${omp_flags} ${typeart_includes} ${typeart_san_flags} \
-      -O1 -Xclang -disable-llvm-passes -S -emit-llvm "${source_file}" -o - |
+      -O1 ${compile_flags} -Xclang -disable-llvm-passes -S -emit-llvm "${source_file}" -o - |
       $llc_tool -x=ir ${llc_flags} -o "${object_file}"
   fi
 }
@@ -176,7 +190,7 @@ function make_with_optim() {
   # Order: heap, optimize, alloca with additional args.
   if [ $skip_typeart == 0 ]; then
     $compiler ${omp_flags} ${typeart_includes} ${typeart_san_flags} \
-      -O1 -Xclang -disable-llvm-passes -S -emit-llvm "${source_file}" -o - |
+      -O1 ${compile_flags} -Xclang -disable-llvm-passes -S -emit-llvm "${source_file}" -o - |
       $opt_tool ${typeart_plugin} ${typeart_heap_mode_args} ${ta_more_args} |
       $opt_tool ${optimize} -S |
       $opt_tool ${typeart_plugin} ${typeart_stack_mode_args} ${ta_more_args} |
@@ -184,13 +198,13 @@ function make_with_optim() {
   else
     # First create types.yaml:
     $compiler ${omp_flags} ${typeart_includes} ${typeart_san_flags} \
-      -O1 -Xclang -disable-llvm-passes -S -emit-llvm "${source_file}" -o - |
+      -O1 ${compile_flags} -Xclang -disable-llvm-passes -S -emit-llvm "${source_file}" -o - |
       $opt_tool ${typeart_plugin} ${typeart_heap_mode_args} ${ta_more_args} |
       $opt_tool ${optimize} -S |
       $opt_tool ${typeart_plugin} ${typeart_stack_mode_args} ${ta_more_args} >/dev/null
 
     $compiler ${omp_flags} ${typeart_includes} ${typeart_san_flags} \
-      -O1 -Xclang -disable-llvm-passes -S -emit-llvm "${source_file}" -o - |
+      -O1 ${compile_flags} -Xclang -disable-llvm-passes -S -emit-llvm "${source_file}" -o - |
       $opt_tool ${optimize} |
       $llc_tool -x=ir ${llc_flags} -o "${object_file}"
   fi
