Library interfaces (#90)
Add interface headers for installed libraries for consumption by other tools.
- Extend runtime interface with more query functions.
- More stable ABI for the libraries by providing interface headers
- Use prefix TYPEART_ instead of TA_ for enums
- Normalize some variable naming, e.g., id is now type_id
- CMake internals: target names with prefix to avoid name clashes

diff --git a/scripts/typeart-tmpl.sh.in b/scripts/typeart-tmpl.sh.in
--- a/scripts/typeart-tmpl.sh.in
+++ b/scripts/typeart-tmpl.sh.in
@@ -37,6 +37,24 @@ function parse_cmd_line() {
       skip_typeart=1
       shift
       ;;
+    --object)
+      if [ -n "$2" ]; then
+        object_file="$2"
+        shift 2
+      else
+        echo "Error: Object file argument for $1 is missing." >&2
+        shift
+      fi
+      ;;
+    --executable)
+      if [ -n "$2" ]; then
+        exe_file="$2"
+        shift 2
+      else
+        echo "Error: Executable file argument for $1 is missing." >&2
+        shift
+      fi
+      ;;
     *) # preserve other arguments
       ta_more_args="$ta_more_args $1"
       shift
