add tests and small fixes
- add tests for null count, null buffer, MPI_Type_create_indexed_block and MPI_Sendrecv
- add requires and unsupported annotations to tests
- remove unused headers from tests
- mark test utility functions inline
- add further checks to existing tests
- add --compile-flags argument to typeart-templ.sh.in
- handle nullptr buffers gracefully during initalization of MPICall
- handle C symbol names correctly when attempting to demangle them

diff --git a/scripts/typeart-tmpl.sh.in b/scripts/typeart-tmpl.sh.in
--- a/scripts/typeart-tmpl.sh.in
+++ b/scripts/typeart-tmpl.sh.in
@@ -14,13 +14,13 @@
 
 function parse_cmd_line() {
   readonly source_file=$1
-  compile_flags="-g -fno-omit-frame-pointer -fno-inline"
   optimize=""
   ta_more_args=""
   with_omp=0
   with_intercept=0
   with_thread=0
   skip_typeart=0
+  compile_flags=""
 
   shift # skip over $1
   while (("$#")); do
@@ -83,6 +83,15 @@ function parse_cmd_line() {
         shift 2
       else
         echo "Error: types.yaml filepath for $1 is missing." >&2
+        shift
+      fi
+      ;;
+    --compile_flags)
+      if [ -n "$2" ]; then
+        compile_flags="$2"
+        shift 2
+      else
+        echo "Error: argument for $1 is missing." >&2
         shift
       fi
       ;;
